version: '3'

services:
  react:
    container_name: react_container
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dump:/dump
    networks:
      - net

networks:
  net:
    external: true
    name: net