version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    env_file: "config.env"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  app:
    env_file: "config.env"
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local